site_name: Cymon API Docs
pages:
- Home: index.md
- Clients: clients.md
#- StatusCodes: status-codes.md
#- Examples: examples.md
#- API: api.md
#- rates: rates.md
#- Installation: installation.md

theme: flatly